# Generated by Django 5.2.3 on 2025-06-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyListApp', '0002_alter_faculty_name_alter_faculty_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='faculty',
            table=None,
        ),
    ]
