# Generated by Django 5.2.3 on 2025-06-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyListApp', '0004_group_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='FacultyListApp.faculty'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
